services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-seafood}
      POSTGRES_USER: ${POSTGRES_USER:-seafood}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-seafood}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-seafood} -d ${POSTGRES_DB:-seafood}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      bash -c "until pg_isready -h db -U ${POSTGRES_USER:-seafood} -d ${POSTGRES_DB:-seafood};
      do echo 'Waiting for database...'; sleep 2; done;
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      SECRET_KEY: ${SECRET_KEY:-change-me}
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      DATABASE_URL: postgres://${POSTGRES_USER:-seafood}:${POSTGRES_PASSWORD:-seafood}@db:5432/${POSTGRES_DB:-seafood}
      DATABASE_ENGINE: ${DATABASE_ENGINE:-django.contrib.gis.db.backends.postgis}
    depends_on:
      db:
        condition: service_healthy

#  pgadmin:
#    image: dpage/pgadmin4:9.8
#    ports:
#      - 5050:80
#    environment:
#      # Required by pgAdmin
#      PGADMIN_DEFAULT_EMAIL: demo@example.com
#      PGADMIN_DEFAULT_PASSWORD: secret
#      # Don't require the user to login
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#      # Don't require a "master" password after logging in
#      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'

volumes:
  postgres_data:
